# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Prepare-For-Rain' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Prepare-For-Rain
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'ChameleonFramework', '~> 2.1'


  target 'Prepare-For-RainTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Prepare-For-RainUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
